## NumPy - fundamental package for scientific computing 
It is a general-purpose array-processing package.It provides a high-performance multidimensional array-object and tools for working with these arrays.
It has bindings of C++ libraries-> Hence,fast training when using array operations

## Arrays
Collection of similar data types as opposed to Python lists(collection of different data types)
Important point: It is a reference type( sharing the same memory )

In [ ]:
## Importing NumPy

In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5]

In [3]:
arr=np.array(list1)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(5,)

In [ ]:
## Multinested array

In [8]:
list2=[3,4,5,6,7]
list3=[5,6,7,8,9]
list4=[8,9,10,11,12]

In [9]:
arr2=np.array([list2,list3,list4])

In [10]:
arr2

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12]])

In [11]:
arr2.shape

(3, 5)

In [12]:
arr2.max

<function ndarray.max>

In [13]:
print(arr2.max)

<built-in method max of numpy.ndarray object at 0x00000210F8137B20>


In [14]:
arr2.max(0)

array([ 8,  9, 10, 11, 12])

In [15]:
arr2.max(1)

array([ 7,  9, 12])

In [17]:
arr2.shape

(3, 5)

In [18]:
arr2

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12]])

In [19]:
arr2.reshape(5,3)

array([[ 3,  4,  5],
       [ 6,  7,  5],
       [ 6,  7,  8],
       [ 9,  8,  9],
       [10, 11, 12]])

In [ ]:
# When reshaping,the number of elements must be same.Else,invalid

In [21]:
arr.shape

(5,)

In [22]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [23]:
arr

array([1, 2, 3, 4, 5])

## Indexing

In [ ]:
# Accessing the array elements (Indexing starts from 0)

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
arr[0]

1

In [26]:
arr2

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12]])

In [27]:
arr2[0][2]

5

In [28]:
arr2[:,:]

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12]])

In [ ]:
# If we want to pick up 3,4(from fist row) and 5,6,(from second row)

In [29]:
 arr2[0:2,0:2]

array([[3, 4],
       [5, 6]])

In [30]:
arr2[1:2,2:5]

array([[7, 8, 9]])

In [31]:
arr2[1:2,2:4]

array([[7, 8]])

## Inbuilt functions in NumPy

In [32]:
arr=np.arange(0,10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr=np.arange(0,10,1)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr=np.arange(0,10,2)

In [37]:
arr

array([0, 2, 4, 6, 8])

In [38]:
np.linspace(1,50,25)

array([ 1.        ,  3.04166667,  5.08333333,  7.125     ,  9.16666667,
       11.20833333, 13.25      , 15.29166667, 17.33333333, 19.375     ,
       21.41666667, 23.45833333, 25.5       , 27.54166667, 29.58333333,
       31.625     , 33.66666667, 35.70833333, 37.75      , 39.79166667,
       41.83333333, 43.875     , 45.91666667, 47.95833333, 50.        ])

In [ ]:
# Copy() Function and Broadcasting

In [39]:
arr

array([0, 2, 4, 6, 8])

In [40]:
arr[3:]=100

In [41]:
arr

array([  0,   2,   4, 100, 100])

In [42]:
arr1=arr # Prevents the 

In [43]:
arr1[3:]=500

In [44]:
arr

array([  0,   2,   4, 500, 500])

In [45]:
arr1

array([  0,   2,   4, 500, 500])

In [46]:
arr2=arr1.copy() # Prevents the updating of multiple arrays that share the same memory or reference

In [47]:
arr2

array([  0,   2,   4, 500, 500])

In [48]:
arr2[3:]=600

In [49]:
arr2

array([  0,   2,   4, 600, 600])

In [50]:
arr1

array([  0,   2,   4, 500, 500])

## Useful for Exploratory Data Analysis

In [51]:
val=2

In [52]:
arr

array([  0,   2,   4, 500, 500])

In [53]:
arr[arr<2]

array([0])

In [54]:
arr[arr<4]

array([0, 2])

In [55]:
arr*2

array([   0,    4,    8, 1000, 1000])

In [56]:
arr/2

array([  0.,   1.,   2., 250., 250.])

In [57]:
arr

array([  0,   2,   4, 500, 500])

In [58]:
arr*4

array([   0,    8,   16, 2000, 2000])

In [59]:
arr

array([  0,   2,   4, 500, 500])

In [60]:
arr/2

array([  0.,   1.,   2., 250., 250.])

In [61]:
arr

array([  0,   2,   4, 500, 500])

In [62]:
np.ones(4)

array([1., 1., 1., 1.])

In [63]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [64]:
# By default,the dtype is float.It can be made as int

In [65]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [66]:
# Random Distribution

In [67]:
np.random.rand(2,5)

array([[0.02102333, 0.37026447, 0.68360434, 0.47938898, 0.56630175],
       [0.70130574, 0.09917639, 0.20507063, 0.45303924, 0.3610617 ]])

In [ ]:
# Random numbers in standard normal distrubution

In [68]:
np.random.randn(4,4)

array([[-0.31096079,  1.75518705,  0.38963312, -0.70781262],
       [ 0.86608458, -1.10364049,  0.66363878, -1.29383735],
       [ 2.06485376,  0.85116077,  0.4166197 ,  0.47671003],
       [ 1.14473099, -0.28052346,  0.28255557, -1.70576275]])

In [70]:
np.random.randint(0,100,8).reshape(2,4)

array([[ 8, 92, 61, 23],
       [80, 75, 16,  6]])

In [71]:
np.random.random_sample((1,5))

array([[0.76579083, 0.79665699, 0.86575726, 0.19010745, 0.38967987]])